# Shell variables
# Generated by 'wal'
wallpaper='/home/chameleon/.config/wpg/wallpapers/mountain.jpg'

# Special
background='#101212'
foreground='#ceccc9'
cursor='#ceccc9'

# Colors
color0='#101212'
color1='#5B6562'
color2='#6D746F'
color3='#7C8079'
color4='#86857B'
color5='#7A8583'
color6='#8F938E'
color7='#ceccc9'
color8='#908e8c'
color9='#5B6562'
color10='#6D746F'
color11='#7C8079'
color12='#86857B'
color13='#7A8583'
color14='#8F938E'
color15='#ceccc9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
