[commands.swipe.three]
left_up = ""
right_up = ""
up = ""
left_down = ""
right_down = ""
down = ""
left = "xdotool key 'Super+shift+Tab'"
right = "xdotool key 'Super+Tab'"

[commands.swipe.four]
left_up = ""
right_up = ""
up = "xdotool key 'ctrl+w'"
left_down = ""
right_down = ""
down = "xdotool key 'ctrl+t'"
left = "xdotool key 'ctrl+shift+Tab'"
right = "xdotool key 'ctrl+Tab'"
